CREATE TABLE TODO_LIST (
    TASK_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_NAME VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TODO_LIST (TASK_NAME)
VALUES ('Study Python');

SELECT * FROM TODO_LIST;

COMMIT;
